name = "backend"
compatibility_date = "2023-12-01"

[vars]
JWT_SECRET='ribhav_secret'
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjk0MzAyYmQtNDUwNS00Y2ZlLWJhN2ItMjc1YTc2NDhjMDc4IiwidGVuYW50X2lkIjoiYWMwMzViOThjMTY0NWUzN2QzZGVlMjZiYzRjMzQ0YWNhNzk2ODBjOTNlY2JmMGQxNDQ4MzYyNjYzOGU2ZjVkMSIsImludGVybmFsX3NlY3JldCI6IjI3YjIwMzRmLWVhMGItNGY0Mi1hZDIyLTY2OGUyZTg0M2M5NyJ9.DH4mCHC608-9elFTw7PWr31QK_Uanz8AOGZL3HA8K7w"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"